// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqwtenxjbafqpirvurss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxd3RlbnhqYmFmcXBpcnZ1cnNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTI3NzcsImV4cCI6MjA2MDkyODc3N30.CDYyc64GO3GZMSS5O3hVGZGGLEZkALfOoeFoRJ4DvS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);